//
//  Constants.h
//  Railtime
//
//  Created by David Steele on 8/14/12.
//  Copyright (c) 2012 Steeleforge. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Constants : NSObject

FOUNDATION_EXPORT NSString *const URL_LINES_STATIONS;
FOUNDATION_EXPORT NSString *const URL_SCHEDULE;
FOUNDATION_EXPORT NSString *const PREFERENCE_LINE;
FOUNDATION_EXPORT NSString *const PREFERENCE_ORIGIN;
FOUNDATION_EXPORT NSString *const PREFERENCE_DESTINATION;
FOUNDATION_EXPORT NSString *const CACHE_SYSTEM;
FOUNDATION_EXPORT NSString *const CACHE_TIMESTAMP;
FOUNDATION_EXPORT NSString *const JSON_TRAIN;
FOUNDATION_EXPORT NSString *const JSON_SCHEDULED;
FOUNDATION_EXPORT NSString *const JSON_ESTIMATED;
FOUNDATION_EXPORT NSString *const DEFAULT_LINE;
FOUNDATION_EXPORT NSString *const DEFAULT_ORIGIN;
FOUNDATION_EXPORT NSString *const DEFAULT_DESTINATION;


@end
